### ISSUE TITLE
Windows build problem and possible fix (luapower_cli related)

### ISSUE THREAD

**Issue by radioflash** [luapower/luapower#7]
Luapower (C-) modules can not be built because the output of luapower_cli can not be parsed correctly.

This is because the output of luapower_cli contains CRLF instead of just LF as newline characters, which breaks the bash-scripts for building (because of stray CR characters):

```bash
for pkg in $packages; do
    echo
    echo "-----------------------------------------------------------"
    echo
    echo "*** Building $pkg for $platform ***"
    echo
    (cd csrc/$pkg && ./build-$platform.sh)
done
```
Note the stray `\r` in the output: 
```bash
[...]
.mgit/build-all.sh: line 36: cd: $'csrc/pixman\r': No such file or directory`
[...]
```

## Possible solution
Switching Lua stdout to binary mode: 
This is simple with LuaJIT (can be directly inserted into luapower_cli.lua and fixes the issue):

```lua
--try and set file mode to binary to avoid writing out CR's
local suc, s = pcall(function()
  local ffi = require 'ffi'
  if ffi.os == "Windows" then
    ffi.cdef[[
      int _setmode(int, int);
      int _fileno(void *);
    ]]
    local _O_BINARY = 0x8000
    ffi.C._setmode(ffi.C._fileno(io.stdout), _O_BINARY)
  end
end)
if not suc then
  error('Unable to try and set stdout mode to binary: \n' .. tostring(s))
end
```

### Alternative
Possibly strip out the carriage returns in the bash scripts? Requires (possibly arcane) changes to every build scripts, though.

## Affected
Any build process that feeds output from luapower_cli into bash scripts.
Example: `./mgit build-all --all`

## Tested on
Windows 10, Mingw toolchain 64bit (gcc 7.3.0 binaries from MSYS2 package manager, MINGW64 bash shell)

Please tell me if I can somehow help with getting this fixed/integrated.
Luapower is awesome btw., thx for all the good work!

**Comment by capr** [comment]
Thanks for the report and the fix. And for the good words :)
Closing this (reopen if needed).
